### ISSUE TITLE
Save Logs During Container Startup

### ISSUE THREAD

**Issue by ceagan** [alexec/docker-maven-plugin#100]
The save-logs feature is cool, but I noticed that the logs are only saved if the container startup is successful. If the health checks fail during the launch of the container, then the logs are not written. It would be helpful for debugging if the user could enable a save-logs option so that during the integration test phase, while the container startup was running, the logs would be written out. Then if the health check failed, the logs would be available to review.

**Comment by alexec** [comment]
Logs should be printed during start-up, regardless of whether the container fails or not. If that is not the case, then this is a bug.

**Comment by marcust** [comment]
I guess the general request here was to put the logs additionally to the save-logs path, in order to have a single point to look at in case of an issue.

**Comment by ceagan** [comment]
@marcust Yes, that is correct. The desired functionality would help when running CI builds. When a build is run on Jenkins, the full output from each of the containers is written to the save-logs path. In the event that one of the containers fails to start up, the save-logs path contains the output from all of the containers that started successfully and the one that didn't.

I think that the current behavior requires looking at the console output to debug container startup issues, which sometimes lacks information because it stops displaying log output for container A once container A has started. When container B starts, the output of container A stops being displayed, but the reason for the failure of container B's startup might be found by reviewing container A's log output. In this case, we usually go look at the logs directly through Docker, but this approach is more difficult when debugging CI builds.
