### ISSUE TITLE
No source / target dependency checking so always builds

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [alexec/docker-maven-plugin#110]
I know it's a non-trivial thing to implement but it appears the plugin will always run a build of a docker image regardless of whether anything has changed or not. Just wondering if there is a neat and tidy trick to try and determine whether a build is avoidable or not as some of our containers are taking upwards of 20 minutes to build when there have been no changes made.

Thanks.

**Comment by alexec** [comment]
Hi, I think this is a nice idea, but I suspect it's quite complex.

You can use standard docker build flags (e.g. `removeIntermediateImages` and `noCache`) to speed up builds, but this is typically a problem for CI builds, and you end up using old images you don't want.

Have you considered breaking your build up? For example, you may find you have a common base image you use a lot that you build just once a day? Or you could use the language stack (https://blog.docker.com/2014/09/docker-hub-official-repos-announcing-language-stacks/). 
Alex

**Comment by AlskiOnTheWeb** [comment]
Yeah, that's what we're starting to look at...a sort of "refactoring" of the images to try and drive out a base.

Thanks,

Al
