### ISSUE TITLE
Alpine linux image build fails on CentOS7

### ISSUE THREAD

**Issue by mikechinaloy** [alexec/docker-maven-plugin#111]
Hi Alex,

Ran into an issue when building an Alpine base image on CentOS 7 vs Mac OSX. For some reason its failing to build the image on CentOS7 with the error:

`[INFO] /bin/sh: apk: not found`

Tried building the image with native commands i.e. docker build and it works fine.

Full details can be found here:

http://stackoverflow.com/questions/40264279/docker-alpine-bin-sh-apk-not-found?noredirect=1#40264670

Note \* on Mac OSX the image builds without issue.

**Comment by alexec** [comment]
I wonder if this is due to new line handling:

http://stackoverflow.com/questions/38199306/why-is-bin-sh-not-found-on-my-alpine-based-docker-compose-build
