### ISSUE TITLE
How to copy multiple files in Dockerfile

### ISSUE THREAD

**Issue by Thorndike** [alexec/docker-maven-plugin#112]
I have a Dockerfile which collects multiple files to one destination folder. 
`COPY etc/leistung-realm.properties /opt/jetty/etc/
COPY etc/preis-realm.properties /opt/jetty/etc/
COPY etc/mitgliedsbeitrag-realm.properties /opt/jetty/etc/
`
With that I have a problem to use only one COPY statement for all files. All versions of the syntax described in the docker documentation seem to cause erros in the validation of the Dockerfile. What is the suggested way to do that with docker-maven-plugin?

`COPY ["etc/leistung-realm.properties", "etc/preis-realm.properties", "etc/mitgliedsbeitrag-realm.properties", "/opt/jetty/etc/"]`
Does not validate.

Plugin Version 2.11.19
Docker Version 1.12.3
Ubuntu 14.04 LTS

**Comment by alexec** [comment]
Could you disable validation?

**Comment by Thorndike** [comment]
I have disabled the validation execution and the project is building fine with those "invalid" Dockerfiles.
