### ISSUE TITLE
Retiring Docker Maven Plugin

### ISSUE THREAD

**Issue by alexec** [alexec/docker-maven-plugin#118]
I'm currently planning on retiring this plugin. I think the Docker community has moved on, and I no longer believe that you should build or test containers using your build tool. 

I'd like to know if anyone would be interested in taking ownership of the plugin. Pleas let me know.

**Comment by rhuss** [comment]
You might want to consider to recommend https://github.com/fabric8io/docker-maven-plugin as an alternative, which seems to be the last actively supported docker-maven-plugin.

Thanks for building and supporting this plugin over the last three years, really gives us quite some inspiration, too.

**Comment by alexec** [comment]
Thank @rhuss. I agreed, that's a great tool and a perfect alternative.

**Comment by marcust** [comment]
As we have a lot of builds running with the plugin I guess @Hubrick will take it over for now. Are you keeping the docker-java-orchestration alive?

**Comment by andyp1per** [comment]
Can you re-release with the updated docker-java/orchestration pieces?

**Comment by alexec** [comment]
Should all be released.

**Comment by andyp1per** [comment]
2.11.17 was released a year ago, and it fails when I use it was the latest docker releases?

**Comment by andyp1per** [comment]
Sorry my mistake. 2.11.24 works great!

**Comment by gsaviane** [comment]
2.11.24 is not yet in Maven central repository. Maybe the publishing process had some issue?

**Comment by marcust** [comment]
It is, I'm using it: 
http://search.maven.org/#artifactdetails%7Ccom.alexecollins.docker%7Cdocker-maven-plugin%7C2.11.24%7Cmaven-plugin

**Comment by gsaviane** [comment]
I don't know what's the difference with maven.org but this repository says that it does not have 2.11.24 yet:
http://mvnrepository.com/artifact/com.alexecollins.docker/docker-maven-plugin

**Comment by Krishnaghimire** [comment]
We are currently using this plugin for running integration testing during build.

**Comment by alexec** [comment]
Hi gents. I'm really pleased that you've found the plugin useful. It's been sad for me to retire it.

If I really thought this was the right way to build containers, I would continue to support it. But really I don't think using Maven to build images is really the right way to build these days. I don't think you should either!

I wrote this when there wasn't a great way to do this, but I think these days Docker support is usually first class in many tools.

I suggest that you either:

1. Migrate to use another actively supported plugin (e.g. fabric8).
2. Build using the standard Docker tools.
