### ISSUE TITLE
Running vanilla images & dynamic port mappings

### ISSUE THREAD

**Issue by rhuss** [alexec/docker-maven-plugin#25]
It would be cool if it would be possible to run images which are *not* build by this plugin but simply pulled directly from a registry (like `mysql` or `postgresql` from dockerhub ?). This is especially useful for integration testing.

Also, for integration tests it would be cool if there would be a way to map dynamically assigned ports to maven properties which then can be reuse in the integration test (e.g. by setting them as system properties before executint the integration tests).

Since its more a wish list, I combined both topics. Feel free to cloes the issue if you don't plan to implement these features.

**Comment by alexec** [comment]
You should be able to access the ports now (see example), for multi-host configuration.
