### ISSUE TITLE
Improvement : docker:tree

### ISSUE THREAD

**Issue by cmoulliard** [alexec/docker-maven-plugin#43]
Docker registry is a great place to find images, info about the images excepted that when an image is build from another, you have to open the Dockerfile to discover the parents : 

example : fabric8/karaf-2.4 -> fabric8/base-sti -> jboss/base-jdk:7 -> jboss/base --> fedora:20

And to understand, what finally will be deployed into a docker container, you must read the difinition of the dockerfile.

It should be great like the mvn dependency:tree to have a docker:tree goal generating a tree with the info calculated / inherited from the parents

**Comment by alexec** [comment]
Good idea, do you have much experience of working with the APIs?

**Comment by alexec** [comment]
No reply. Closing.
