### ISSUE TITLE
Image build order unknown

### ISSUE THREAD

**Issue by rbattenfeld** [alexec/docker-maven-plugin#48]
This maven docker plugin works great. Thanks a lot
`
My question is: Is it possible to define order how the plugin creates the images? I do have one base image which is the base for other images.

Thanks,
Ralf

**Comment by alexec** [comment]
Hi,

Order is based on dependency between containers (I.e. Links), but otherwise non deterministic. You can get around this with a multi module maven project. 

Alex

**Comment by alexec** [comment]
You can control the build order using a docker.yml file now. https://github.com/alexec/docker-java-orchestration/tree/master/docker-java-orchestration-core/src/test/docker-repo-v2

**Comment by rbattenfeld** [comment]
Thanks a lot. This simplifies a lot. Cool!
