### ISSUE TITLE
Excluded container is still trying to find by id

### ISSUE THREAD

**Issue by dacrome** [alexec/docker-maven-plugin#49]
In my integration tests I'm running against mysql and postgres containers. I created for both maven profiles to start the tests only per database. When I excluded the opposite image/container, the docker-maven-plugin is still trying to find the excluded container. The docker-maven-plugin exclude the image/container in every step (clean, start), but before the tests starting the following exception was thrown:
Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.7.0:start (start-docker-container) on project integration-tests: no such id: integration-tests_mysql

**Comment by alexec** [comment]
I'm betting there is a missing switch for this. I'll try and find some time to look into later on. In the meantime, if you have an example project where this is a problem, can you share it with me?

**Comment by dacrome** [comment]
Hi, thanks for the fast response!

Just checkout the running-against-docker-container branch of my [repo](https://github.com/dacrome/connector4java-integration-tests). The excludes are in the pom [line 584](https://github.com/dacrome/connector4java-integration-tests/blob/running-against-docker-container/pom.xml#L584) and [line 686](https://github.com/dacrome/connector4java-integration-tests/blob/running-against-docker-container/pom.xml#L686).

To run the tests:
```
mvn verify -P postgres
```
or
```
mvn verify -P mysql
```

**Comment by alexec** [comment]
Hi, fixed in version 2.8.4-SNAPSHOT (I think). Do you think you can verify? You'll need to add Sonatype as your builds pluginRepository, see here:

https://github.com/alexec/search-in-a-box/blob/master/pom.xml

**Comment by dacrome** [comment]
verified with 2.8.2-SNAPSHOT. thanks!
