### ISSUE TITLE
Exposed port via conf.yml is not mapping correctly

### ISSUE THREAD

**Issue by dacrome** [alexec/docker-maven-plugin#50]
When set in conf.yml the ports like in the [USAGE](https://github.com/alexec/docker-maven-plugin/blob/master/USAGE.md)
```
ports:
  - 13306 3306
```
the container will be started with the following port configuration:
```13306/tcp, 0.0.0.0:32778->3306/tcp```

So the mapping is wrong.

**Comment by alexec** [comment]
Hi, again, I don't suppose you have an example you could share with me? It'll make my life easier!

**Comment by dacrome** [comment]
It's the same example that I mentioned in issue https://github.com/alexec/docker-maven-plugin/issues/49, so it includes the setup to reproduce both issues.

Just checkout the `running-against-docker-container` branch of my [repo](https://github.com/dacrome/connector4java-integration-tests). I set the ports in the mysql and postgres conf.yml files in `src/main/docker`

To run the tests:
```
mvn verify -P postgres
```
or
```
mvn verify -P mysql
```

**Comment by alexec** [comment]
Test case, create a port forward from 13306 on host to 3306 on a MySQL Container:

````
docker run -p 127.0.0.1:8888:3306 -dMYSQL_ROOT_PASSWORD=secret mysql
Alex-Collinss-MacBook:docker alexc$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED              STATUS              PORTS                       NAMES
d183fb88e8af        mysql:5             "/entrypoint.sh mysq   About a minute ago   Up About a minute   127.0.0.1:8888->3306/tcp   thirsty_payne   
```

**Comment by alexec** [comment]
Fixed. Please test and let me know if you have any issues.

**Comment by dacrome** [comment]
works like a charm. thanks again!
