### ISSUE TITLE
The container name should be configurable

### ISSUE THREAD

**Issue by dacrome** [alexec/docker-maven-plugin#51]
Use case: When you have multiple maven profiles to build a differently configured image it should be possible to start the containers side by side ... or because of problems with the [circleci build](https://circleci.com/gh/dacrome/connector4java-integration-tests/42) because the tests run against a mysql and postgres database container ;)
```
[INFO] Image IDs do not match, removing container and creating new one from image
.
.
[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.2-SNAPSHOT:start
(start-docker-container) on project integration-tests:
com.github.dockerjava.api.InternalServerErrorException: Cannot destroy container 
6a639524d2b0506bd7e966891a0d55d6f7ce49091482040569f71d9beab1313a: 
Driver btrfs failed to remove root filesystem 
6a639524d2b0506bd7e966891a0d55d6f7ce49091482040569f71d9beab1313a: 
Failed to destroy btrfs snapshot: operation not permitted -> [Help 1]
```
I know this is more an issue of circleci but it would be a nice feature anyway and of course a workaround for the circleci limitation...

**Comment by alexec** [comment]
Try setting `<permissionErrorTolerant>true</permissionErrorTolerant>` in your `pom.xml`?

**Comment by dacrome** [comment]
yes, that's do the trick on circleci! I already set it to true but didn't test it again... Anyway, do you think to make the container name configurable is a common use case?

**Comment by alexec** [comment]
Have you tried setting the tag?

**Comment by dacrome** [comment]
yes, the tag has no influence on the container name. [Repo.java#L91](https://github.com/alexec/docker-java-orchestration/blob/master/docker-java-orchestration-core/src/main/java/com/alexecollins/docker/orchestration/Repo.java#L91)

**Comment by alexec** [comment]
Ok. I see what your getting at. Should be easy to update Conf.java to provide an optional container name. Maybe something like:

~~~
container:
   name: myName
~~~
Fancy being an awesome OSS contributor?

**Comment by alexec** [comment]
Ok. Please try latest SNAPSHOT.

**Comment by dacrome** [comment]
Nice, that was fast! Thanks!
