### ISSUE TITLE
Mapped Portbindings as system properties

### ISSUE THREAD

**Issue by rbattenfeld** [alexec/docker-maven-plugin#59]
It would be good to provide the mapped ports as system properties. I think, currently is just the container IP address as system property available, right?

The use case is very simple. There are environments using docker which doesn't allow to make the container IP address available remotely. They are not 'natted', for example security reasons. All communications goes over the mapped ports on the docker host.

**Comment by alexec** [comment]
Do you fancy becoming an OSS contributor?

**Comment by rbattenfeld** [comment]
I am already contributing to other open source projects:-) Do you ask me to implement this and send a pull request? Sure, it would be a pleasure;-)

**Comment by alexec** [comment]
I'd love if you want to look into it. I've written some instructions here:

https://github.com/alexec/docker-maven-plugin/blob/master/CONTRIB.md

The part of code the would need to be update is here:

https://github.com/alexec/docker-maven-plugin/blob/master/src/main/java/com/alexecollins/docker/mojo/StartMojo.java#L19

I've had a few pull requests without good tests, I like to have integration tests for changes (using Maven invoker plugin, standard stuff).

**Comment by rbattenfeld** [comment]
Thanks a lot for your instructions. I will certainly follow your guide lines with all required tests.

**Comment by rbattenfeld** [comment]
Hi Alex, after very busy with projects in my company, I jumping to this task. Is it still fine to work on this?

I had trouble to setup my local repo. I had to execute './build.sh init build' in order to get the sub modules. Did I missed something? At least, the docker-maven-plugin compiles now. So I can restart:-)
