### ISSUE TITLE
Push broken

### ISSUE THREAD

**Issue by eemmiirr** [alexec/docker-maven-plugin#61]
The itegration tests are broken. And my latest pull request is broken. I suppose it's because of the commit https://github.com/alexec/docker-java-orchestration/commit/076f2380802b41ec8592c71892d416d8433c2503

**Comment by alexec** [comment]
Can you prove an example?

**Comment by eemmiirr** [comment]
The integration tests are failing which I added to test this

**Comment by eemmiirr** [comment]
If you revert the commit b78bed46359f32ad0f1fa42fde7b8bc37666339c in docker-java-orchestration the integration tests are passing

**Comment by alexec** [comment]
I've reverted the commit on master.
