### ISSUE TITLE
user properties not filtered in conf.yml

### ISSUE THREAD

**Issue by andyp1per** [alexec/docker-maven-plugin#62]
I'm guessing you know this since the code is clearly broken. But user properties are not filtered properly.

if if set \<my.prop\>foo\</my.prop\> in the pom and put ${my.prop} in conf.yml and then invoke mvn with:
mvn -Dmy.prop=bar clean install then ${my.prop} will be expanded to foo rather than bar.

**Comment by andyp1per** [comment]
You shouldn't be calling         p.putAll(System.getProperties()); IMO - this has already been done for you when you get the project properties. At a minimum you should call this after getting the project properties

**Comment by alexec** [comment]
Hi Andy,

Do you fancy becoming a contributor as you seem to know more about this than I do!

Alex

**Comment by alexec** [comment]
Fixed in latest push.

**Comment by andyp1per** [comment]
Thanks, works! So many projects, too little time. I'm happy to create pull requests - but even happier when bug reports get actioned ;)
