### ISSUE TITLE
conf.yml does not deal with absolute paths

### ISSUE THREAD

**Issue by andyp1per** [alexec/docker-maven-plugin#64]
If I use the dependency plugin properties task I get helpful properties that point at jars in my local repo. If I try and use this is conf.yml it fails because it is assuming everything added is relative to the ${basedir} which in this case it is not. Seems like it should detect whether the path is aboslute or relative and therefore determine whether to add ${basedir} or not.

**Comment by alexec** [comment]
I'm trying to think about how you would do this so that it works both on Linux and Windows. Do you have any ideas?

**Comment by alexec** [comment]
There should be a fix in the latest version. Please let me know if this works for you.
