### ISSUE TITLE
Goals not bound by default to lifecycle phases

### ISSUE THREAD

**Issue by andyp1per** [alexec/docker-maven-plugin#66]
Maven promotes convention over configuration. As such most plugins bind their goals by default to appropriate lifecycle phases. Configuration can be used to modify this behaviour but should not be necessary to enable it in the first place.
This plugin should bind its goals to appropriate lifecycle phases.

**Comment by alexec** [comment]
Hi,

I'm a bit busy for the next week or two. If you fancy this, and contributing, you could follow these intructions:

https://github.com/alexec/docker-maven-plugin/blob/master/CONTRIB.md

**Comment by alexec** [comment]
No reply. Closing.
