### ISSUE TITLE
run container with   --privileged=false   -  Give extended privileges to this container

### ISSUE THREAD

**Issue by ntrvic** [alexec/docker-maven-plugin#67]
Hi!,

Does anyone know if it is possible pass properties such as --privileged=false inside the yml config?

Thanks,

Victor

**Comment by alexec** [comment]
Hi, not at the moment. I don't think it'd be too hard to add. Fancy giving it ago? Here's the instructions:

https://github.com/alexec/docker-maven-plugin/blob/master/CONTRIB.md

**Comment by alexec** [comment]
Now available in 2.9.3.

**Comment by ntrvic** [comment]
Thanks!
