### ISSUE TITLE
Setting up projects to build from both linux and boot2docker

### ISSUE THREAD

**Issue by filipncs** [alexec/docker-maven-plugin#68]
It seems unnecessarily cumbersome to set up a project to be build both from linux hosts (with local docker running unsecured) and boot2docker.

The workaround for unsecured docker in the readme (an explicit http://localhost:2375 host entry in the configuration) overrides how boot2dockers docker host is discovered by environment variables. The best solution I've found is to put the http://localhost:2375 host value in a maven property, in a profile that's only activated when the DOCKER_HOST environment variable isn't set. E.g.:

    <plugin>
        <groupId>com.alexecollins.docker</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        ...
        <configuration>
            <host>${docker.host}</host>
        </configuration>
    </plugin>

    ...

    <profile>
        <id>local-docker</id>
        <properties>
            <docker.host>http://localhost:2375</docker.host>
        </properties>
        <activation>
            <property>
                <name>!env.DOCKER_HOST</name>
            </property>
        </activation>
    </profile>

Is there something I'm missing?

If the plugin defaulted to http when the host isn't actively set anywhere and the DOCKER_TLS_VERIFY environment variable isn't set to "1", I think this would cover most use cases, but I'm not sure I have the big picture.

**Comment by alexec** [comment]
Hi, I use the docker-java library, so this change would need to be made there. Fancy giving it a go? Instructions here:

https://github.com/alexec/docker-maven-plugin/blob/master/CONTRIB.md

**Comment by filipncs** [comment]
That could be a solution, if no other users of docker-java depend on the current functionality. In any event, the team I'm on decided to make everybody set the environment variable, even on linux, which solves the problem, without the maven profile trick.
