### ISSUE TITLE
Support for Docker Toolbox

### ISSUE THREAD

**Issue by hypery2k** [alexec/docker-maven-plugin#76]
Are there any plans to support the [Docker Toolbox](https://github.com/docker/toolbox)?

**Comment by dacrome** [comment]
What in particular do you want to be supported? If you like to manage images and containers on a machine you can set the `docker.host` property e.g.
```
mvn verify -Ddocker.host=https://192.168.99.100:2376
```

This is the host of the `default` machine on my mac.

**Comment by ceagan** [comment]
You can also edit the start.sh script ("C:\Program Files\Docker Toolbox\start.sh") which comes with Docker Toolbox to name the VM boot2docker-vm. This enhances the compatibility a bit. I updated the script a bit and changed the beginning to the following. I also changed the line ending to UNIX for better compatibility when running this script from Cygwin.

```sh
#!/bin/bash

trap '[ "$?" -eq 0 ] || read -p "Looks like something went wrong... Press any key to continue..."' EXIT

VM=boot2docker-vm
DOCKER_MACHINE=./docker-machine.exe
if [ ! -f $DOCKER_MACHINE ]; then
  cd /c/Program\ Files/Docker\ Toolbox
fi
```

**Comment by alexec** [comment]
I'm aware that the port forwarding no longer works, as they renamed the VM from "boot2docker-vm" to "default". There will be an update soon.

**Comment by alexec** [comment]
This has been updated and should be in Maven Central.
