### ISSUE TITLE
issues getting maven plugin working with default mac docker-toolbox install

### ISSUE THREAD

**Issue by jbarnettwomply** [alexec/docker-maven-plugin#77]
On an ubuntu machine with docker 1.6.2 apt-get installed from the wily universe repository, I can successfully build and deploy an image via this maven plugin.

On a mac with docker 1.8.1 installed via docker-toolbox/docker-machine, I run into the following issues:

1) docker-machine defaults DOCKER_HOST to "tcp://192.168.99.100:2376", but the maven plugin complains that tcp is not a supported protocol.  I've worked around this by using the regex-property goal of the build-helper maven plugin to s/tcp/https/, but seems like this should work out of the box?

2) I can't get private repository auth working no matter what I do.  this seems at least somewhat related to notes I've made in https://github.com/docker-java/docker-java/issues/316 -- but not sure if there's anything specific to the maven plugin that could also be an issue?

**Comment by alexec** [comment]
Do you have `DOCKER_TLS=` set?

**Comment by jbarnettwomply** [comment]
DOCKER_TLS_VERIFY and DOCKER_TLS_CERT_PATH were set by the docker-machine env command.  DOCKER_TLS was not set, but setting it to 1 does not change the behavior for either issue (1) or (2)

**Comment by alexec** [comment]
Hmmm, I'm not sure what's happening here. You can also set these in the pom.xml, or via system properties. I'm pretty sure it should recognise `DOCKER_TLS_VERIFY=1` and switch to HTTPS.

**Comment by alexec** [comment]
This __may__ be fixed in the latest release.
