### ISSUE TITLE
Support more Maven Project Properties

### ISSUE THREAD

**Issue by jljouannic** [alexec/docker-maven-plugin#79]
Currently, only a subset of [Maven Project Properties](http://books.sonatype.com/mvnref-book/reference/resource-filtering-sect-properties.html#resource-filtering-sect-project-properties) can be used for filtering of `conf.yml` and `Dockerfile` :
- project.groupId
- project.artifactId
- project.version
- project.name
- project.description
- project.build.finalName

Could it be possible to add all `project.build.*` properties to this list?

**Comment by alexec** [comment]
I think you should be able to? https://github.com/alexec/docker-maven-plugin/blob/master/src/main/java/com/alexecollins/docker/mojo/AbstractDockerMojo.java#L225

Have you an example where this does not work?

**Comment by jljouannic** [comment]
Putting the following in the `conf.yml` file

```yaml
…
add:
  - ${project.build.directory}/some-artifact-${project.version}.tar.gz
…
```
gives

```bash
…
java.io.FileNotFoundException: Source '/home/me/some-folder/my-project/${project.build.directory}/some-artefact-1.0.0.tar.gz' does not exist
…
```
As you can see, `project.version` is resolved, but not `project.build.directory`.

**Comment by jljouannic** [comment]
Thinking about it, even if `project.build.directory` was resolved it wouldn't work. When resolved, `project.build.directory` gives an absolute path.

In this case the resolved path to add would be `/home/me/some-folder/my-project//home/me/some-folder/my-project/target/some-artefact-1.0.0.tar.gz`. Still not good :-/

**Comment by dacrome** [comment]
You are by default in the build directory, just add your artifact with

```
…
add:
  - target/some-artifact-${project.version}.tar.gz
…
```
Like described in the [example usage](https://github.com/alexec/docker-maven-plugin/blob/master/USAGE.md#usage-1).

**Comment by jljouannic** [comment]
I do not agree. I think you are by default in the `project.basedir` directory. I could follow the example and directly use `target` in my `conf.yml` file. But if I choose to customize the Maven build directory :

```xml
…
<build>
  <directory>${project.basedir}/foo</directory>
</build>
…
```
I would have to put `foo` in `conf.yml` as well. Not cool.

**Comment by dacrome** [comment]
I'm sorry, for sure you are by default in the `project.basedir` that's why you need to set the `target` folder before your artifact filename.

**Comment by jljouannic** [comment]
Which can be problematic if `target` is not the project build directory configured in the `pom.xml` file like in my example above.

**Comment by dacrome** [comment]
hm? you can set whatever you want in the `conf.yml` to add to your build. Like:

```
…
add:
  - foo/some-artifact-${project.version}.tar.gz
…
```
Or do you have a dynamic project build directory?

**Comment by jljouannic** [comment]
Sure. I understand that. I simply would like to avoid repeating myself ([DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself)).

Anyway, I found a workaround by changing (even if I keep the default `target` value) the build directory in the pom through a custom property which I use in the `conf.yml` file :

- `pom.yml`

    ```xml
        …
        <properties>
            <!-- Workaround to https://github.com/alexec/docker-maven-plugin/issues/79 -->
            <buildDirectory>target</buildDirectory>
        </properties>
        <build>
            <directory>${project.basedir}/${buildDirectory}</directory>
        </build>
        …
    ```
- `conf.yml`

    ```yaml
        …
        add:
          - ${buildDirectory}/some-artifact-${project.version}.tar.gz
        …
    ```

**Comment by alexec** [comment]
I'm confused here, so let me clarify how it works, maybe that will help?

Say you have `src/main/docker/app`:

1. The configuration directory is copied from `src/main/docker/app` to `target/docker/app`.
2. Text files have properties replaced, that includes `conf.yml`.
3. Any files in the `add` block are copied into `target/docker/app`, e.g. if you add `target/my-app.jar`, it'll copy `target/my-app.jar` to `target/docker/app/my-app.jar`.
4. Effectively 'docker build target/docker/app` in run to create your app.

So....

1. Make sure your `add` paths are relative to project base dir, e.g.

~~~
add:
- target/my-app.jar
~~~


2. Make sure your `Dockerfile` has just the file name.

~~~
ADD my-app.jar /
~~~

Does that help?

**Comment by jljouannic** [comment]
I understand all that.

I simply wanted to avoid having `target` (or whatever is the build directory defined in my `pom.xml` – see my 4th comment above) "hardcoded" in `conf.yml`.

**Comment by Thorndike** [comment]
I would like to mount a local directory to the running container for tests. Since I need an absolute path for local volumes it would be nice to use project.basedir directly instead of creating an otherwise obsolete property (which works btw.).
