### ISSUE TITLE
Use a third-party image as a build dependency

### ISSUE THREAD

**Issue by jljouannic** [alexec/docker-maven-plugin#80]
In the `USAGE.md` file, there is a paragraph about using another image as a build dependency (L95 in source). After searching in source code for a while I see no trace of implementation of this feature. No matter where I put `image: some-third-party-image` in `conf.yml` I keep getting exception about field `image` not being supported.

**Comment by alexec** [comment]
Ah - you are correct. This is an error in the `USAGE.md`. I've been working on this feature, but it is not complete yet. You can do it by just putting `FROM some-image-name` into a `Dockerfile`.

**Comment by alexec** [comment]
Corrected USAGE.md.
