### ISSUE TITLE
Is dockerhub v2 (registry v2) supported?

### ISSUE THREAD

**Issue by andyp1per** [alexec/docker-maven-plugin#84]
All the examples are v1, but docker tells us that v2 is much better :)

**Comment by alexec** [comment]
This should be supported now.

**Comment by andyp1per** [comment]
Do we need to use a different URL to take advantage of this?

**Comment by marcust** [comment]
@andyp1per  Well, the thing is that the maven plugin does not talk to the registry directly. All pull requests etc. are relayed to your local docker daemon who talks to the registry. So basically it depends on the version of docker that is installed on your machine. 
But with the latest release you should be able to use docker 1.5 all the way up to 1.9, so you should be fine.
