### ISSUE TITLE
Question: How to set port mappings and sleep time?

### ISSUE THREAD

**Issue by rbattenfeld** [alexec/docker-maven-plugin#85]
Hi

I can start/stop a container but I can't set the sleep time and the port mappings. Probably because of wrong configuration.

The conf.yaml looks like this:

    machine:
      services:
        - docker
      environment:
        DOCKER_HOST: http://mtzhrnesig01:4243
    ports:
       - 8080 6800
       - 9990 6801
    sleep: 10000
    healthChecks:
       pings:
          - url: http://mtzhrnesig01:6800/
            timeout: 60000
         - url: http://mtzhrnesig01:6801/
           timeout: 60000
    test:
      override:
       - mvn verify -Pwildfly-remote-adapter

Neither the sleep time nor the port mappings are applied.

I am also not sure what are correct pom settings:

    <plugin>
	<groupId>com.alexecollins.docker</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<version>2.11.3</version>
	<executions>
		<execution>
			<goals>
 			    <goal>start</goal>
			    <goal>stop</goal>
		       </goals>
		</execution>
	</executions>
       
       
       
       
       
       
       
     </plugin>

I commented out the dependencies since I have no clue what is the replacement for a linux docker environment. Boot2docker for sure not.

**Comment by alexec** [comment]
Can you please paste error?

**Comment by rbattenfeld** [comment]
There is no error. It starts the container but always with random ports assigned. I need a configuration that maps the exposed port 8080 to port 6800 on the docker host. And, as I wrote, the sleep time is not recognized at all, resulting in executing of the tests too early.

So, I am looking for a configuration which allows me to set the sleep time, or healtchecks and as well correct port mappings. It looks to me that the orchestration configuration is not applied. 

First question: What do I need to specify instead of the boot2docker dependency? It runs on linux, there is no windows...

Second question: Can you have a look at the yaml file above? Does it looks ok?

Thanks for your help
Ralf

**Comment by alexec** [comment]
Try reversing ports?

**Comment by rbattenfeld** [comment]
I tried this already... Can you tell which dependency I have to declare in the pom?

**Comment by alexec** [comment]
Closing due to no action.
