### ISSUE TITLE
package goal failing on jenkins slave

### ISSUE THREAD

**Issue by Thorndike** [alexec/docker-maven-plugin#87]
I have set up a jenkins ci slave to build docker images. During the maven build the package goal fails while pulling the base image with:

[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.11.4:package (default-cli) on project user-dockerize: Could not build image: Authentication is required. -> [Help 1]

I am using a private v2 registry with self signed cert and have username and password in the plugin configuration. If I login as the slave user directly and start a docker build manually the base image is pulled from my registry. The maven build is also working on my local machine with docker 1.9.

docker version:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

**Comment by alexec** [comment]
Can you please provide `pom.xml` and `mvn -X <goals>` output?

**Comment by Thorndike** [comment]
The 16 MB zip was not accepted. Can I send you a link to the files on my google drive?

**Comment by marcust** [comment]
@Thorndike Can you retry with 2.11.5?

@alexec there might be an issue with docker-java/docker-java#316, depending on which version of the docker.cfg file he has, but as he writes that he provides username and password that should not be the issue

**Comment by Thorndike** [comment]
@marcust Same result with 2.11.5

[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.11.5:package (default-cli) on project user-dockerize: Could not build image: Authentication is required. -> [Help 1]

I am for now stuck with docker 1.7.1 as everything but my development machine is running on RHEL 6 and that got abandoned by the docker people.

**Comment by marcust** [comment]
@Thorndike Can you provide the layout of your .dockercfg (remove the actual credentials of course)

**Comment by Thorndike** [comment]
There is no .dockercfg on RHEL6 but that should be everything I have configured on the machines that fail.

 /etc/sysconfig/docker:
# This file is managed by Puppet and local changes
# may be overwritten

DOCKER="/usr/bin/docker"

other_args=" -H unix:///var/run/docker.sock -H 0.0.0.0:2375 --insecure-registry docker-registry.cp.creditreform.de"
# This is also a handy place to tweak where Docker's temporary files go.
export TMPDIR="/tmp/"
# Resolves: rhbz#1176302 (docker issue #407)
DOCKER_NOWARN_KERNEL_VERSION=1

config.json:

{
	"auths": {
		"docker-registry.cp.creditreform.de": {
			"auth": "**********",
			"email": "1@2.com"
		}
	}
}

pom.xml:

**Comment by marcust** [comment]
Can you try to refit your .dockercfg to look like:
```
{
	"myregistry.de": {
            "auth": "**********",
            "email": "1@2.com"
	}
}
```
(remove the extra auths object)

and try if that works?

**Comment by Thorndike** [comment]
My config.json is created by the puppet docker plugin while doing a login to the registry. I have tried the following:

- sync the email adress (just to be sure)
- changed config.json to leave out the auths element
- removing the credentials from the pom

All gives the same result as before. I have restarted the docker daemon after each change to the config.json. The only thing that does work is to manually pull the base image to the local docker. After that the docker-maven-plugin is able to build the new image.

**Comment by marcust** [comment]
Well, I can assure you I have it running in production :)

So, what I was heading at is that there are two ways of authorization for the maven plugin. One is with the ```.dockercfg```. What I forgot is that you actually have to enable that in your config:
```
                        <configuration>
                            <cfgPath>${user.home}/.dockercfg</cfgPath>
                        </configuration>
```

Due to some changes in the format of ```.dockercfg``` between Docker 1.6 and 1.7 the docker-java library currently only supports the old format, which is without the ```auths``` element. The new format is the one with ```auths```, but as I said, that is not supported. That is just the format, though, the maven plugin should work with all versions of docker, just by using the old ```.dockercfg``` format.

I actually never used the direct configuration of username and password, but as I read the code:
 * you have to set all four username, password, email and server address
 * I'm currently somewhat confused as to the actual format, because the Docker remote API docs say this way should work, but the way that is actually used by the ```.dockercfg``` is fields ```email``` and ```auth``` and not ```email```, ```username```, ```password``` and ```servername```. 

Does your docker daemon logs give more insight in this?

**Comment by Thorndike** [comment]
The log file does not help:

time="2015-12-09T11:23:03.296236262+01:00" level=info msg="GET /version" 
time="2015-12-09T11:23:03.732554092+01:00" level=info msg="GET /v1.19/version" 
time="2015-12-09T11:23:03.906612351+01:00" level=info msg="GET /v1.19/containers/json?all=0&size=0" 
time="2015-12-09T11:23:03.926037807+01:00" level=info msg="GET /v1.19/containers/json?all=0&size=0" 
time="2015-12-09T11:23:03.931762815+01:00" level=info msg="GET /v1.19/containers/json?all=1&size=0" 
time="2015-12-09T11:23:03.938754314+01:00" level=info msg="GET /v1.19/images/json?all=0" 
time="2015-12-09T11:23:04.211293291+01:00" level=info msg="GET /version" 
time="2015-12-09T11:23:04.262887994+01:00" level=info msg="GET /v1.19/version" 
time="2015-12-09T11:23:05.415405412+01:00" level=info msg="GET /version" 
time="2015-12-09T11:23:05.452749427+01:00" level=info msg="GET /v1.19/version" 
time="2015-12-09T11:23:06.045826517+01:00" level=info msg="GET /version" 
time="2015-12-09T11:23:06.079521929+01:00" level=info msg="GET /v1.19/version" 
time="2015-12-09T11:23:07.711387371+01:00" level=info msg="POST /v1.19/build?t=myregistry.de/crim/crauth-api:0.0.1-SNAPSHOT" 
time="2015-12-09T11:23:17.887292233+01:00" level=error msg="Error from V2 registry: Authentication is required." 

I changed the pom configuration from email, username, password and servername to

		<cfgPath>${user.home}/.docker/config.json</cfgPath>

and suddenly the base image could be pulled. It seems my initial configuration was somehow not valid.

On a side note: The logging of the complete pull process is really blowing my Jenkins log up by some MB.

**Comment by marcust** [comment]
There is a ```quiet``` option, but I'm not sure if that applies to pull output.

**Comment by Thorndike** [comment]
Which leaves two open points:

- when will the new config be supported
- what went wrong with setting the credentiels in pom

Not that urgent but altering all puppet installed machines might cause some trouble in the long run.

**Comment by alexec** [comment]
Hi --  is this still a problem? If so, have you tried with the latest snapshot release?

**Comment by Thorndike** [comment]
I do no longer get that far with the plugin. After upgrading from 2.11.5 to 2.11.9 it already fails on my workstation with 

[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.11.9:clean (default-cli) on project api-dockerize: protocol = unix host = null -> [Help 1]

Which might have to do with the new version of docker-java used in the plugin. I was not able to override that due to an incompatible api.

**Comment by Thorndike** [comment]
I have updated to version 2.11.10 and the current result is different. manually pulling the image in advance still works but the plugin now throws a differet error:

`[INFO] Step 1 : FROM docker-registry.cp.creditreform.de/dev-env/jetty
[INFO] Error parsing HTTP response: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /v2/dev-env/jetty/manifests/latest was not found on this server.</p>\n</body></html>\n"
com.github.dockerjava.api.DockerClientException: Could not build image: Error parsing HTTP response: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /v2/dev-env/jetty/manifests/latest was not found on this server.</p>\n</body></html>\n"
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:71)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:48)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:357)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:296)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:825)
	at com.alexecollins.docker.mojo.PackageMojo.doExecute(PackageMojo.java:16)
	at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:168)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Calling "GET https://docker-registry.cp.creditreform.de/v2/dev-env/jetty/manifests/latest" directly with a REST client results in a valid xml response.

**Comment by marcust** [comment]
Hey, thanks for trying again.

You did see this html snippet?
´´´<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /v2/dev-env/jetty/manifests/latest was not found on this server.</p>\n</body></html>\n" com.github.dockerjava.api.DockerClientException: Could not build image: Error parsing HTTP response: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /v2/dev-env/jetty/manifests/latest was not found on this server.</p>\n</body></html>\n
´´´

Who is answering then? Because something is definitely answering with a 404, which feels there must be something wrong in the configuration.

Can you have a look into your /var/log/syslog or wherever your docker daemon writes its output to?

**Comment by Thorndike** [comment]
I don't find anything useful in the logs. The configuration should be correct because:

docker pull docker-registry.cp.creditreform.de/dev-env/jetty

works locally (container name directly copied from error message) and the REST call to the expected address works too.
Is it possible to get the called URL in the plugin log?

**Comment by marcust** [comment]
The thing is that it is actually not the plugin directly that is calling that url but the docker daemon. And that should be the same thing from the the command line and from the plugin.

I might have my docker running in debug log or something, because when I build something I see this in my logs:

```
Mar  9 15:05:56 docker[1152]: time="2016-03-09T15:05:56.252196224+01:00" level=debug msg="POST /build?t=registry/busybox-test"
Mar  9 15:05:56 docker[1152]: time="2016-03-09T15:05:56.297965839+01:00" level=debug msg="Trying to pull busybox from https://registry-1.docker.io v2"
Mar  9 15:05:58 docker[1152]: time="2016-03-09T15:05:58.510611162+01:00" level=debug msg="Pulling ref from V2 registry: busybox:latest"
```

So he is packaging the dockerfile and everything and POSTING that to the daemon, who in turn will then pull the image. I think that might be the way to debug here. Apparently you need to add -D to the command line of your docker daemon.

**Comment by Thorndike** [comment]
Funny thing is in the access log of the https proxy on the registry server: There is no 404 at all. I have no clue which server is called by the plugin. The manual pull requests are logged just fine.

**Comment by Thorndike** [comment]
This is the log content for a failed build

`Mär 09 15:19:19 rhscpm006.ecofis.de docker[15995]: time="2016-03-09T15:19:19.621618935+01:00" level=debug msg="POST /v1.22/build?t=docker-registry.cp.creditreform.de/as/ask-auskunft:0.0.1-SNAPSHOT"
Mär 09 15:19:19 rhscpm006.ecofis.de docker[15995]: time="2016-03-09T15:19:19.922091951+01:00" level=debug msg="Trying to pull docker-registry.cp.creditreform.de/dev-env/jetty from https://docker-registry.cp.creditreform.de v2"
Mär 09 15:19:19 rhscpm006.ecofis.de docker[15995]: time="2016-03-09T15:19:19.973555022+01:00" level=debug msg="Error trying v2 registry: Get https://docker-registry.cp.creditreform.de/v2/dev-env/jetty/manifests/latest: no basic auth credentials"
Mär 09 15:19:19 rhscpm006.ecofis.de docker[15995]: time="2016-03-09T15:19:19.973637987+01:00" level=debug msg="Trying to pull docker-registry.cp.creditreform.de/dev-env/jetty from http://docker-registry.cp.creditreform.de v2"
Mär 09 15:19:19 rhscpm006.ecofis.de docker[15995]: time="2016-03-09T15:19:19.984361075+01:00" level=debug msg="Error trying v2 registry: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\">\\n<html><head>\\n<title>404 Not Found</title>\\n</head><body>\\n<h1>Not Found</h1>\\n<p>The requested URL /v2/dev-env/jetty/manifests/latest was not found on this server.</p>\\n</body></html>\\n\""
Mär 09 15:19:19 rhscpm006.ecofis.de docker[15995]: time="2016-03-09T15:19:19.984446082+01:00" level=debug msg="Skipping v1 endpoint https://docker-registry.cp.creditreform.de because v2 registry was detected"
Mär 09 15:19:19 rhscpm006.ecofis.de docker[15995]: time="2016-03-09T15:19:19.984473653+01:00" level=debug msg="Skipping v1 endpoint http://docker-registry.cp.creditreform.de because v2 registry was detected"
`

with `				<serverAddress>https://docker-registry.cp.creditreform.de/</serverAddress>`

**Comment by marcust** [comment]
And how does that look if you do a manual "docker build" ?

**Comment by Thorndike** [comment]
All may boil down to a misleading message. I now manually have logged in to the registry with the user that is running the build and now I get

[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.11.10:package (default-cli) on project auskunft-docker: Failed to parse dockerCfgFile: Invalid Auth config file -> [Help 1]

Which seems to be the error message for the config.json with the "auths":  element.

manually starting the build with 
 ` docker build --rm --no-cache --pull -t docker-registry.cp.creditreform.de/as/ask-auskunft:0.0.1-SNAPSHOT .`
works fine

**Comment by Thorndike** [comment]
Tested again with 2.11.11. 
Result with reference to config.json:
Caused by: java.io.IOException: Invalid Auth config file
	at com.github.dockerjava.core.AuthConfigFile.loadConfig(AuthConfigFile.java:123)

It seems the "auths": Element is still not recognized

Result with username/password:
[INFO] unauthorized: authentication required
com.github.dockerjava.api.DockerClientException: Could not build image: unauthorized: authentication required


Access to a private registry is still not working in any way.

**Comment by Thorndike** [comment]
Retested with 2.11.13 and still failing.

Using username/password results in 
com.github.dockerjava.api.DockerClientException: Could not build image: unauthorized: authentication required

with the reference to the config.json I still get (now with docker 1.11.1)
com.github.dockerjava.api.DockerClientException: Failed to parse dockerCfgFile
Caused by: java.io.IOException: Invalid Auth config file

Manually building the image with docker build still works fine.

Is there any chance of a fix here? Until now I could get around with manually preloading the required base image but we are getting closer to an automated build chain and this would be a blocker.

**Comment by marcust** [comment]
My basic plan here is to wait for the final release of the docker-java client library 3.0 and then revisit the the whole authorization issue. 

By now there should be no point to support the old pre 1.7 auth file format anymore.

**Comment by Thorndike** [comment]
Thx for the Info, I have subscribed to the issue in docker-java about the config.json.

**Comment by lorijoan** [comment]
@Thorndike - are you still having problems?  We were seeing some of the same issues on deploy but I've been able to resolve these (on 2.11.13) by using the old style .dockercfg.  Have you tried the following:

<serverAddress><your docker address here></serverAddress>
<cfgPath>${user.home}/.dockercfg</cfgPath>

Then for .dockercfg, the file looks like:
`{
        "<your docker address here>: {
        "auth": "<your auth credentials here>",
        "email": "<your email here>"
        }
}`

The auth will be the exact same one in the config.json that's generated automatically if you did a docker login to your remote server on the machine.

**Comment by Thorndike** [comment]
This maven plugin is working if I change the docker config and leave out the "auths" element of the new config. Unfortunately I am using a jenkins docker plugin on the same server for some non maven builds. That one is controlling docker directly and fails with the older config using a current docker.

**Comment by Thorndike** [comment]
Retested with 2.11.16 which seems to contain docker-java 3.0.0 but no success :(

**Comment by scheuchzer** [comment]
Same here. Doesn't work with 2.11.16

**Comment by alexec** [comment]
I've updated to docker-java:3.0.2 yesterday. Version 2.11.17 should be on Maven Central shortly. Can I please request you review the instructions for authentication here: https://github.com/docker-java/docker-java#configuration, and see if it works with environment variables (typically the most reliable way of doing this).

**Comment by Thorndike** [comment]
I have tried to set the config as a system property via MAPEN_OPTS but neither DOCKER_CONFIG nor setting username/password got me any different results. Also setting DOCKER_CONFIG as environment variable did nothing. Still getting 

[INFO] unauthorized: authentication required
com.github.dockerjava.api.exception.DockerClientException: Could not build image: unauthorized: authentication required

Anything I can try differently?
