### ISSUE TITLE
validate goal does not support port type at expose

### ISSUE THREAD

**Issue by Thorndike** [alexec/docker-maven-plugin#89]
The validate goal fails on my Dockerfile with

[ERROR] Wrong EXPOSE 8301/udp format on line

It seems that port types are not supported by the validator. They are valid for docker though. Any workaround?

**Comment by alexec** [comment]
Hi,

You can avoid the goal for the time being.  If you are able to provide an example, I could take a look at in a few days when I have free time (I'm moving house). If you fancy fixing it, here is the file that the problem must be in:

https://github.com/alexec/docker-java-orchestration/blob/master/docker-java-orchestration-core/src/main/java/com/alexecollins/docker/orchestration/DockerfileValidator.java

Alex

**Comment by Thorndike** [comment]
Try to rebuild the public consul-agent image. That should be enough.

https://github.com/gliderlabs/docker-consul/tree/master/0.5/consul-agent

For now I can work around that.

**Comment by alexec** [comment]
This should now be fixed is the latest snapshot. Do you think you could please try it out and tell me?

**Comment by alexec** [comment]
No respones. Assuming fixed, or don't care.
