### ISSUE TITLE
volumes does not seem to do anything

### ISSUE THREAD

**Issue by andyp1per** [alexec/docker-maven-plugin#90]
I can't seem to get the volumes command to do anything useful. I'm trying to copy files out of my container back into userland. Do you have an example and/or test for this?

**Comment by alexec** [comment]
Hi Andy,

Presumably you meant `volumes` in the `conf.yml`? Do you have an example? I'm not likely to get a chance to look at it in the next few days as I'm moving house, but I'll probably have time in the future.

Alex

**Comment by andyp1per** [comment]
Hi Alex,
I'm actually pretty sure that volumes doesn't do what I want since they are only available at runtime. What I want is some way of pulling artifacts out of the built VM at build time. It seems that docker cp would achieve this, but there is no binding for it. I'd be interested in adding this if you thought it was a good idea and could point me at where in the code it should sit

**Comment by alexec** [comment]
Docker only mounts volumes at run time, so must start the container.

You could use the Antrun plugin to do a `docker cp` to get the asset you.
You'll want to set a name on the container.

If you want to contribute:

https://github.com/alexec/docker-maven-plugin/blob/master/CONTRIBUTING.md

You'll want to know a bit about working with Maven plugins, but it is a
useful skill to learn.

**Comment by alexec** [comment]
Have you tried the new `copy` goal?

**Comment by andyp1per** [comment]
Yeah, that's why I wrote it :)
