### ISSUE TITLE
Delete stopped containers after maven completes

### ISSUE THREAD

**Issue by eddykaya** [alexec/docker-maven-plugin#91]
I use the plugin to setup a integration test environment. It would be nice to delete stopped containers after finishing the integration tests automatically.

**Comment by alexec** [comment]
Hi Eddy,

This does seem like a useful enhancement. You can, if you like, use the `removeIntermediateContainers` to clean up a bit.

As the `clean` goal remove containers, you could add an `<execution/>` block to your `pom.xml` to delete them. Something like...

~~~xml
<execution>
<id>clean-up</id>
<phase>post-integration-test</phase>
<goals><goal>>clean</goal><goals>
</execution>
~~~

Finally, I find that CI servers (and local dev machines need regular clean-up, so I made this:

https://github.com/alexec/bin/blob/master/dk

Alex

**Comment by eddykaya** [comment]
Thanks, that solves my problem. However, it would be nice to be able to just delete the running containers, not the images themselves.

Eddy

**Comment by marcust** [comment]
You can set
```
<configuration>
    <cleanContainerOnly>true</cleanContainerOnly>
</configuration>
```

that should do the trick.

**Comment by eddykaya** [comment]
Hey marcust,

tried that, but it has no effect:

here is my plugin:

`<plugin>
						<groupId>com.alexecollins.docker</groupId>
						<artifactId>docker-maven-plugin</artifactId>
						<configuration>
							<host>http://localhost:2375</host>
							<removeIntermediateImages>true</removeIntermediateImages>
							<cache>false</cache>
							<exclude>minkki-data-pool</exclude>
							<serverAddress>http://docker.qudosoft.de:5000</serverAddress>
							<cleanContainerOnly>true</cleanContainerOnly>
						</configuration>
						<executions>
							<execution>
								<id>buildAndStartEnvironment</id>
								<phase>package</phase>
								<goals>
									<goal>package</goal>
									<goal>start</goal>
								</goals>
							</execution>
							<execution>
								<id>clean-up</id>
								<phase>post-integration-test</phase>
								<goals>
									<goal>stop</goal>
									<goal>clean</goal>
								</goals>
							</execution>
						</executions>
					</plugin>`

**Comment by marcust** [comment]
Which version are you using? It works for me and the feature is not that recent, so I'm puzzled.

**Comment by alexec** [comment]
Hi -- is the clean-up still an issue?

**Comment by alexec** [comment]
No reply. Closing.
